name: check-does-build

# 1. 增加了 workflow_dispatch 以支持手动触发
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Loom Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-cleanup: never

      # 2. 增加保存构建产物的步骤
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/build/libs/*.jar
          # 如果你还需要保存其他文件（例如 log、exe 等），可以在 path 下继续添加
          # 如果想保存整个 build 目录，可以直接写 **/build/
          retention-days: 5 # 文件的保存天数（默认 90 天，这里设置为 5 天以节省空间）
